FROM node:24-alpine

ARG VITE_SERVER_HOST
ARG VITE_OAUTH_REDIRECT_HOSTNAME
ARG VITE_FIREBASE_CONFIG
ARG VITE_STRIPE_PUBLIC_KEY
ARG VITE_TURN_SERVERS
ARG VITE_TURN_USERNAME
ARG VITE_TURN_CREDENTIAL

ENV NODE_ENV=production \
    VITE_SERVER_HOST=$VITE_SERVER_HOST \
    VITE_OAUTH_REDIRECT_HOSTNAME=$VITE_OAUTH_REDIRECT_HOSTNAME \
    VITE_FIREBASE_CONFIG=$VITE_FIREBASE_CONFIG \
    VITE_STRIPE_PUBLIC_KEY=$VITE_STRIPE_PUBLIC_KEY \
    VITE_TURN_SERVERS=$VITE_TURN_SERVERS \
    VITE_TURN_USERNAME=$VITE_TURN_USERNAME \
    VITE_TURN_CREDENTIAL=$VITE_TURN_CREDENTIAL

COPY . /usr/src

WORKDIR /usr/src

RUN npm ci

RUN npm run build

ENTRYPOINT ["/bin/sh", "-c" , "npm start"]
