# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm ci
      - run: npm run build --if-present
        env:
          CI: true
          REACT_APP_FB_APP_ID: 2814364712014216
          REACT_APP_FIREBASE_CONFIG: '{"apiKey":"AIzaSyA2fkXeFokJ-Ei_jnzDso5AmjbIaMdzuEc","authDomain":"watchparty-273604.firebaseapp.com","databaseURL":"https://watchparty-273604.firebaseio.com","projectId":"watchparty-273604","storageBucket":"watchparty-273604.appspot.com","messagingSenderId":"769614672795","appId":"1:769614672795:web:54bbda86288ab1a034273e"}'
          REACT_APP_RECAPTCHA_SITE_KEY: 6LeDGP4UAAAAAGYZZenyU-3fRdhL3p0BaBmiK9mM
          REACT_APP_STRIPE_PUBLIC_KEY: pk_live_eVMbIifj5lnvgBleBCRaCv4E00aeXQkPxQ
          NODE_ENV: production
      - name: Push to remote
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/master' }}
        run: |
          git config --global user.name "github-actions[bot]"	
          git config --global user.email "watchparty+github-actions[bot]@users.noreply.github.com"	
          rm .gitignore	
          git checkout -b release
          git add --all
          git commit --quiet -m "Built from ${{ github.sha }}" 	
          git push origin release -f
